/*
 * CMinus Language Syntax Configuration
 * This file contains configuration for each keyword, operator and symbol used in the language.
 * 
 * Version 1.0.0 (Standard 2026)
 */

#pragma once

#define __cminus_config_1__

/* Keywords */
#define K_main          "main"
#define K_exit          "exit"
#define K_if            "if"
#define K_else          "else"
#define K_for           "for"
#define K_while         "while"
#define K_never         "never"
#define K_do            "do"
#define K_switch        "switch"
#define K_match         "match"
#define K_case          "case"
#define K_default       "default"
#define K_goto          "goto"
#define K_scope         "scope"
#define K_not           "not"
#define K_return        "return"
#define K_break         "break"
#define K_continue      "continue"
#define K_when          "when"
#define K_final         "final"
#define K_const         "const"
#define K_let           "let"
#define K_alloc         "alloc"
#define K_new           "new"
#define K_free          "free"
#define K_del           "del"
#define K_is            "is"
#define K_as            "as"
#define K_in            "in"
#define K_of            "of"
#define K_import        "import"
#define K_public        "public"
#define K_module        "module"
#define K_using         "using"
#define K_volatile      "volatile"
#define K_static        "static"
#define K_inline        "inline"
#define K_flat          "flat"
#define K_clang         "clang"
#define K_asm           "asm"
#define K_datatype      "datatype"
#define K_errtype       "errtype"
#define K_boil          "boil"
#define K_boils         "boils"
#define K_g             "g"
#define K_bucket        "bucket"
#define K_flow          "flow"
#define K_finally       "finally"
#define K_typedef       "typedef"
#define K_union         "union"
#define K_struct        "struct"
#define K_data          "data"
#define K_class         "class"
#define K_extends       "extends"
#define K_this          "this"
#define K_base          "base"
#define K_interface     "interface"
#define K_enum          "enum"
#define K_table         "table"
#define K_options       "options"
#define K_variant       "variant"
#define K_insert        "insert"
#define K_ensure        "ensure"
#define K_sizeof        "sizeof"
#define K_typeof        "typeof"
#define K_typeid        "typeid"
#define K_alignof       "alignof"
#define K_maxof         "maxof"
#define K_minof         "minof"
#define K_null          "null"        
#define K_none          "none"        
#define K_undefined     "undefined"   
#define K_NaN           "NaN"
#define K_Infinite      "Infinite"
#define K_true          "true"
#define K_false         "false"

/* Type Keywords */
#define K_i8          "i8"
#define K_i16         "i16"
#define K_i32         "i32"
#define K_i64         "i64"
#define K_u8          "u8"
#define K_u16         "u16"
#define K_u32         "u32"
#define K_u64         "u64"
#define K_f32         "f32"
#define K_f64         "f64"
#define K_isize       "isize"
#define K_usize       "usize"
#define K_char        "char"
#define K_wchar       "wchar"
#define K_rune        "rune"
#define K_bchar       "bchar"
#define K_bool        "bool"
#define K_trnry       "trnry"
#define K_void        "void"

#define K_string      "string"
#define K_str         "str"

/* Predefined Type Aliases */
#define K_byte        "byte"
#define K_short       "short"
#define K_int         "int"
#define K_long        "long"
#define K_ubyte       "ubyte"
#define K_ushort      "ushort"
#define K_uint        "uint"
#define K_ulong       "ulong"
#define K_float       "float"
#define K_double      "double"